### PR TITLE
Added pull request template

### PR DESCRIPTION
**Pull request by DrMagPie**

### CODE REVIEW

**Comment by DrMagPie** [comment]
@Conor12345 What do you think?
This way this check list will appear in front of us pretty much for every submission :)

**Comment by Conor12345** [comment]
Looks good to me, may need to include SoundCloud example for embedding if anyone decides to use it, but I doubt it will happen so it's good as is for now.

**Comment by DrMagPie** [comment]
Unfortunately it's not as easy to create similar embed for sound cloud... so in the end for user will be easier to add embed manually.

**Comment by Conor12345** [comment]
Okay, fair enough. Looks all good to me then.

**Pull request merged**
