### PR TITLE
Fix atom feed format

### PR DESCRIPTION
**Pull request by 9p4**
This PR fixes the atom feed format

### CODE REVIEW

**Comment by justchen1369** [comment]
Is switching to http:// necessary?

**Comment by 9p4** [comment]
Yes, since it is part of the spec to specify it as http. This XML feed is invalid without it.

**Comment by 9p4** [comment]
Spec: https://validator.w3.org/feed/docs/atom.html
Failed Validation: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Falt-f4.blog%2Fatom.xml

**Comment by justchen1369** [comment]
LGTM then 👍

**Comment by 9p4** [comment]
Seems it was introduced in this mass change. About the time ALT-F4 stopped working in my RSS aggregator.

https://github.com/AlternativeFFFF/Alt-F4/commit/8442b99628251e23501ca6b0f3552eaa51766f4c

Some other files (svg, etc) may need to be switched back as well (but I doubt there is much of an issue there).

**Pull request merged**
