### PR TITLE
initial buttons.scss refactoring

### PR DESCRIPTION
**Pull request by justchen1369**

### CODE REVIEW

**Comment by Conor12345** [comment]
Is there any particular reason for this refactoring? Also could we do anything about #294 here?

**Comment by DrMagPie** [comment]
@Conor12345 nope, not related to #294 
Here he just removes duplicate code and uses SCSS magic to import it from one generic class.

@justchen1369 I think it's better to leave `.active` incase we want to use it in future.

**Comment by justchen1369** [comment]
Doesn't `:active` serve the purpose of `.active`?

**Comment by DrMagPie** [comment]
yes that true. but there could be the case when it can't be determined on a render stage, then `.active` comes into play.
in theory... XD

**Comment by justchen1369** [comment]
Someone could just reference this PR for the correct additions :D

**Comment by justchen1369** [comment]
If there are no issues then I'll just merge this.

**Review by DrMagPie — APPROVED** [review]

**Pull request merged**
