### PR TITLE
Added .active

### LINKED ISSUE #311: Page buttons don't show which page is active
Expected:

### PR DESCRIPTION
**Pull request by DrMagPie**
fixes #311

### CODE REVIEW

**Comment by justchen1369** [comment]
is `.active` needed there?

**Comment by DrMagPie** [comment]
jup pagination buttons are using it

**Comment by DrMagPie** [comment]
live site 
image

this PR
image

**Review by xthexder — APPROVED** [review]
Looks good on the CI build

**Review by justchen1369 — APPROVED** [review]
Looks like this is the best way to do this.

**Pull request merged**
