### PR TITLE
Space exploration Mod Spotlight

### PR DESCRIPTION
**Pull request by Conor12345**
### Author info
Name: ironic toblerone
Suggested release date: 20/11/2020

### CODE REVIEW

**Comment by Nanogamer7** [comment]
**Fact Checking:**
- [[MP](https://mods.factorio.com/mod/space-exploration)] The described resources match the descriptions on the mod page, except Cryonite (spelled cyonite in line 43), and Arcospheres, which the mod author missspelled on his mod page
- [MP] Scienences also match the mod page
- [[MA](https://github.com/AlternativeFFFF/Alt-F4/pull/302#issuecomment-728887292)] Cargo rocket capacity of 500 is correct
- ~~Images~~ (media only includes examples and supports the writen information, no new *'facts'*)

---

IG = In-Game
WIKI = Wiki (duh), expect the specific page to be linked for clarity
LO = Logic, article doesn't agree with itself
MP = Mod Page
MA = Mod Author

**Comment by ClaudeMetz** [comment]
Looks great, maybe you can contact either ironic toblerone or earendel about those misspellings to see which of them is correct.

**Comment by EarendelGames** [comment]
Cryonite is the correct spelling.
Arcospheres has been corrected on the mod portal page (thanks).
Rocket capacity is 500.

**Review by Conor12345 — COMMENTED** [review]
All embeds done. Generic image embed needs merging before friday but needs some more work before then.

**Review by nicgarner — COMMENTED** [review]
copyedit complete 👍

**Review by nicgarner — APPROVED** [review]
copyedit complete 👍

**Review by Conor12345 — COMMENTED** [review]
Technical review complete.
Preview: https://media.alt-f4.blog/fileshare/alt-f4-14-preview.png 
Ready for translation.

**Review by Conor12345 — COMMENTED** [review]
bot testing - Move along, nothing to see here.

**Review by Conor12345 — COMMENTED** [review]
bot test 2 electric boogaloo

**Review by Conor12345 — COMMENTED** [review]
bot testing

**Review by Conor12345 — COMMENTED** [review]
Mmm yummy bots working

**Pull request merged**
