### PR TITLE
Mobile redesign / big improvements

### LINKED ISSUE #46: Improve mobile site
Make the site more mobile friendly.

Todo (things marked as done may or may not be in master yet):
- [X] Shrink translation button slightly on all screen widths
- [X] Reduce padding in navbar more on smaller screen widths
- [X] Remove gaps:
  - [X] Between navbar and main panel at the top
  - [X] Between the sides and the main panel at the side
  - [X] Between the main panel and the footer
  - [X] Between the sides and the footer at the side
- [X] Reduce padding of main panel and some inset panels
- [X] Make parts of the footer stack instead be next to each other inline
- [ ] Only use larger background on larger screens
- [ ] Fix YouTube embed height - https://fettblog.eu/blog/2013/06/16/preserving-aspect-ratio-for-embedded-iframes/
- [ ] Adjust translate icon centering

### LINKED ISSUE #55: Fix discuss buttons
Small fix to discuss on Reddit and discord buttons to place text better inside the box

### PR DESCRIPTION
**Pull request by CanadaHonk**
Fixes #46, what is left to add to this PR is also in there.

Testing:
- [X] Looks good on a range of devices via Chromium-based DevTools "emulation":
  - Pixel 2
  - Moto G4
  - Galaxy S5
  - iPhone 5 / SE
  - iPhone X
- [X] Actual testing on a range of devices:
  - Moto X4 (Chrome, Firefox) - looks good ~~except apparently some scrolling lag which also happened before these changes~~ reportedly works fine on Firefox, seems Chrome-specific issue and not an actual site issue
  - Pixel 3a (Chrome) - screen is large enough that it appears like a tablet and looks fine - maybe improve media query for mobile tweaks, however it still looks fine currently
  - iPhone X (Safari) - looks good (plus feedback to add more spacing between main panel and footer, that has now been added)
  - Huawei P20 (Chrome, Firefox) - looks good (plus same feedback note as above) - also has similar weird Chrome-specific issues, same as Moto X4 on Chrome

New todo:
- Features
  - [X] Background
- Fixes
  - [X] YouTube embed does not limit aspect ratio
  - ~~Translate icon in button is not centered (?)~~

Also features:
- Fix for #55 
- Better scaling for YouTube Embeds

### CODE REVIEW

**Comment by Conor12345** [comment]
Resolves #55

**Comment by Conor12345** [comment]
Browser check list:     

| Browser | Usage | Tested | Worked expected |
-- | -- | -- | --
Chrome | 65.99% | Yes | Yes
Safari | 16.82% | No | Unknown
Firefox | 4.09% | Yes | Yes
Samsung Internet | 3.47% | Yes | Yes
Edge | 2.98% | No | Most likely (Chromium-based)
Opera | 2.09% | No | Most likely (Chromium-based)

**Comment by CanadaHonk** [comment]
Live preview at: https://alt-f4-mobile-testing.netlify.app

**Comment by CanadaHonk** [comment]
(Also now ready to be reviewed.)

**Comment by Conor12345** [comment]
Tested on:
- Firefox mobile
- Chrome mobile
- Opera mobile
- Android Web view
- Samsung internet 

Looking really good on mobile, could do with a safari mobile check and a few desktop browser checks.

**Review by Conor12345 — APPROVED** [review]
Look awesome!

**Comment by justchen1369** [comment]
https://links.lambdatest.com/L96E96H8WY9BWY6K231CL681MIWLS830VGJH78JRMCSFBPBMEPBJL7A3KZBTZWNV

**Pull request merged**
