### PR TITLE
Whole card is a link

### LINKED ISSUE #285: I expected the whole post box, in the index, to be a link
I expected that tapping anywhere in the box for each index entry would take me to the content, not just the title link. 

Given it is the most likely thing I want to do, making that active across the whole box, and then allowing links in the index entry (eg: author) to take me to more specialized places, is the least surprising choice.

### PR DESCRIPTION
**Pull request by DrMagPie**
Closes #285
[Preview](https://drmagpie.alt-f4.blog)

### CODE REVIEW

**Comment by Conor12345** [comment]
Is this likely to cause accessibility issues with screen readers? I know @Oj18 has issue #120 open but I'm not sure how the two interact.

**Review by Conor12345 — APPROVED** [review]

**Comment by justchen1369** [comment]
Tbh I don’t think that this is beneficial, seeing as now there’s no feedback about the card being clickable.

**Comment by Conor12345** [comment]
Ye thats a good point, didn't notice that actually

**Comment by justchen1369** [comment]
Another thing is that, imo, it doesn't seem like the card should be clickable- just the title.

**Comment by Conor12345** [comment]
I quite like that the whole card is clickable, but it would be nice if you could still hover over the title and have it be highlighted. Especially good for mobile too

**Pull request merged**
