### PR TITLE
Change a few images to webp, 1.8 mb transferred --> 1.3 mb transferred

### PR DESCRIPTION
**Pull request by justchen1369**
helps with #93

### CODE REVIEW

**Comment by justchen1369** [comment]
live site can be found [here](https://quizzical-euclid-35490d.netlify.app/)

**Comment by DrMagPie** [comment]
Preview: https://ffff-ofdt5pg0f.vercel.app

Browser check list:     
- [x] Chrome 51.38%
- [x] Android Webview 18.38%
- [x] Safari 17.38%
- [x] Firefox 7.25%
- [x] Samsung Internet 2.98%
- [x] Edge 1.04%
- [x] Opera 0.82%
- [x] Safari (in-app) 0.48%
- [ ] YaBrowser 0.19%
- [x] Internet Explorer 0.05%

**Comment by justchen1369** [comment]
I'd also like to change the thumbnails to webp if that's ok.

**Comment by Conor12345** [comment]
Need to consider how this factors into the new mobile design PR #94 too. 
Also I have no issues with thumbnail format being changed assuming @ClaudeMetz is good with it since he's the one dealing with thumbnail creation.

**Comment by DrMagPie** [comment]
Hi @justchen1369 

Thank you for your efforts!

But I can't approve this PR :(
Unfortunately Safari doesn't support `webp` format
and quite a lot of our viewers are on safari :( 

image

IMG_3B9C05D4554F-1

**Comment by justchen1369** [comment]
looks like it'll be supported fairly soon though: https://caniuse.com/webp

**Comment by justchen1369** [comment]
> In June 2020 it was announced that macOS Big Sur will include Safari 14.

> macOS Big Sur (version 11.0) is the next major release of macOS, Apple Inc.'s operating system for Macintosh computers. 

:(

**Comment by DrMagPie** [comment]
hmmm that's a good news.

**Comment by justchen1369** [comment]
until then, can we just leave this open and not commit or close it?

**Comment by DrMagPie** [comment]
we will keep it in backlog till release of iOS 14 and macOS BigSur

**Comment by DrMagPie** [comment]
Also to be tested on rest of browsers https://github.com/AlternativeFFFF/Alt-F4/pull/105#issuecomment-689577915

**Comment by justchen1369** [comment]
I think I fixed everything that needed to be fixed.

**Comment by justchen1369** [comment]
netlify live link: https://5f58fea32b183e00071ae2d2--quizzical-euclid-35490d.netlify.app/

**Comment by CanadaHonk** [comment]
So we are using regular JPEG as fallback?

**Comment by justchen1369** [comment]
It depends on what it was originally tbh.

**Comment by CanadaHonk** [comment]
And this also only changes background and Spidertron idle gif?

**Comment by justchen1369** [comment]
This will also affect the footer bg.

**Comment by CanadaHonk** [comment]
Also from the Netlify at least, I get 1.5mb transferred not 1.3mb but yea.

**Comment by justchen1369** [comment]
About the 1.5: That would be because of lossless conversion of gif to webp for spidertron-idle and including a 4 kB script for webp support detection.

**Comment by CanadaHonk** [comment]
Also I get 2.3mb transferred on current live version so lol

**Comment by CanadaHonk** [comment]
But yeah, I didn't realise >50% of the total network transference is *only* the background image, jeez.

**Comment by justchen1369** [comment]
I feel like the background could stand up to more lossy compression.

**Comment by justchen1369** [comment]
Can we merge if there are no further issues that need to be resolved?

**Comment by DrMagPie** [comment]
when all browsers are tested

**Comment by justchen1369** [comment]
I can confirm that it works on desktop chrome.

**Comment by justchen1369** [comment]
seems to work fine on opera.

**Review by DrMagPie — APPROVED** [review]

**Review by Conor12345 — APPROVED** [review]

**Review by CanadaHonk — APPROVED** [review]
Looks good.

**Pull request merged**
