### PR TITLE
AltF4-6 Translation push

### PR DESCRIPTION
**Pull request by Firerazer**
Italian, German, French and Spanish translation for AltF4-6

**Need to edit them to add the reddit link for discussion before being accepted**

### CODE REVIEW

**Comment by Firerazer** [comment]
also, you need to enable german to be displayed on the website as it this their first translation ;)

**Comment by justchen1369** [comment]
you can just edit config.yml to add the lang :)

**Comment by Firerazer** [comment]
like this? :)

**Comment by justchen1369** [comment]
looks ok- how much of the page is supposed to be translated?

**Pull request merged**
