### PR TITLE
add highres include

### PR DESCRIPTION
**Pull request by justchen1369**

### CODE REVIEW

**Review by DrMagPie — COMMENTED** [review]
I would name parameters a bit differently. so they would better represent what they are doing. like (`href` for link to original and `src` for image it self. but this is minor.)

with regards to include itself, have you tested it? I feel like it's missing some css classes. (like `media`)

**Comment by justchen1369** [comment]
I was unsure, so that's why i did the PR.

**Comment by Conor12345** [comment]
Would it be possible to merge some of our includes? Currently we have a bunch of different ones for different scenarios which is real annoying. We will need to keep old ones for compatibility reasons but it would be nice to have two smarter includes (one for video, one for image) that have all the functionality included (caption, highres etc.)

**Comment by justchen1369** [comment]
Either that or document all of the includes somehow?

**Comment by justchen1369** [comment]
I was also thinking of moving all of the site includes to their own folder.

**Comment by Conor12345** [comment]
Being resolved with PR #305

**Pull request closed without merging**
