### PR TITLE
Added table of content

### LINKED ISSUE #113: Create an index for each post
Zirr had the idea to add an index alongside each post, with clickable links ofc, that the reader can refer to to get an overview of the content, especially since the posts can get quite long, like we found out. Here is the screenshot of Zirr's idea.

### PR DESCRIPTION
**Pull request by DrMagPie**
Closes #113
[Preview](https://ffff-git-issue-113.drmagpie.vercel.app/ALTF4-4/)

Added table of content with no additional styling.
We need to decide ho we want it to look and style accordingly.

Table of contents has class `toc`
Also have added `anchor` class to anchors 

also adresses #136

### CODE REVIEW

**Comment by justchen1369** [comment]
[Lambdatest results](https://links.lambdatest.com/0DC2VB75L4VYXC0DTYLBCL42G0UIQOOOXH43VWEI88ZAZI3FS3EP6R61T22ZH2KW)
Confirmed on Safari that icons are not working properly.

**Comment by Conor12345** [comment]
What do people think of having this kinda setup for the index page. Will have to be desktop only but it can utilize the area to the left where the background usually shows maybe? 
https://www.quackit.com/css/codes/css_floating_menu.cfm

**Comment by Conor12345** [comment]
image
- [x] Would it be possible to center the popped out windows in the middle of the column?
- [x] Could the index page be expanded by default when popped out?

**Comment by LovelySanta** [comment]
I think it would be nice maybe to inline it in the text, like it should not span the full width of the text, like 33% or 50% should be more than sufficient?

**Comment by Conor12345** [comment]
> I think it would be nice maybe to inline it in the text, like it should not span the full width of the text, like 33% or 50% should be more than sufficient?
>
>
Absolutely worth a try, might look weird but we can see.

**Comment by DrMagPie** [comment]
Rebased onto master

**Comment by Conor12345** [comment]
**Popped out table of contents**
- [x] Need to adjust this to not overlap the page on this screen size (1920px width minus scroll bar)
   - Probably worth shrinking the size of the box rather than the width at which it triggers also 1080p is a common resolution which would be nice to have popouts in.
image

- [x] Very similar issue except now the text does not have enough padding
image

**Non-popped out**
- [ ] Need to try lovely santas suggestions still https://github.com/AlternativeFFFF/Alt-F4/pull/117#issuecomment-691537262

**Comment by DrMagPie** [comment]
Safari:
image
FireFox on Mac OS:
image
FireFox Windows:
image
Chrome Windows:
image

but why?

**Comment by Conor12345** [comment]
**TESTING TIME!!!** _woop woop_

- [x] Chrome
  - [x] Mobile
  - [x] Desktop narrow
  - [x] Desktop wide
- [x] Safari
  - [x] Mobile
  - [x] Desktop narrow
  - [x] Desktop wide
- [x] Firefox
  - [x] Mobile
  - [x] Desktop narrow
  - [x] Desktop wide
- [x] Opera
  - [x] Mobile
  - [x] Desktop narrow
  - [x] Desktop wide
- [x] Edge
  - [x] Desktop narrow
  - [x] Desktop wide
- [x] Samsung internet
  - [x] Mobile
- [x] Android webkit
  - [x] Mobile

**Comment by justchen1369** [comment]
Hold on I got dis

**Comment by justchen1369** [comment]
desktop chrome ✔️ 
desktop narrow chrome ✔️

**Comment by justchen1369** [comment]
opera ✔️

**Comment by DrMagPie** [comment]
Safari ✔️

**Review by CanadaHonk — APPROVED** [review]
Looks good.

**Review by Conor12345 — APPROVED** [review]

**Pull request merged**
