### PR TITLE
Page Not Translated Banner

### PR DESCRIPTION
**Pull request by DrMagPie**
@Firerazer Please take a look at new value in [locale.yml](https://github.com/DrMagPie/drmagpie.github.io/blob/nt/_data/en/locale.yml#L7) It holds value for not translated banner.

I'm not sure about styles. but we always can adjust them later

### CODE REVIEW

**Comment by Firerazer** [comment]
I think Therenas want to finalise the text for this. Will wait on this, ask for translation at all supported languages, and push new files :)

**Comment by justchen1369** [comment]
As for the styling, I think that it should be smaller, more "flat"(aka less box shadow), and have a darker color.

**Comment by Firerazer** [comment]
Changing the English sentences to include the language it is referring to + FR translation done

**Comment by Firerazer** [comment]
Translation asked - we can wait for most translation to be send before pushed @DrMagPie ?

**Comment by DrMagPie** [comment]
@Firerazer yes

**Comment by Firerazer** [comment]
Translations:
- [x] CS
- [x] DE
- [x] ES
- [x] FR
- [x] IT
- [ ] PL
- [x] RU
- [x] UA
- [x] ZH

**Review by Firerazer — APPROVED** [review]
@DrMagPie for me, ready to go :)

**Review by Conor12345 — APPROVED** [review]

**Pull request merged**
