### PR TITLE
Aspect

### PR DESCRIPTION
**Pull request by DrMagPie**
Attempting to fix SpaceShip imports if they are even broken....

### CODE REVIEW

**Comment by Conor12345** [comment]
For reference: https://ffff-git-aspect.drmagpie.vercel.app/aspect

**Comment by Conor12345** [comment]
Not sure whats going on, but im getting weird behaviour in firefox and chrome on windows:
Video: https://media.alt-f4.blog/fileshare/conor-aspect.mp4
Needs further investigation.

**Review by CanadaHonk — APPROVED** [review]
Code looks good

**Comment by Conor12345** [comment]
For some reason the spaceship embed for youtube just wont quite work right aspect ratio wise. Gonna close this PR as the other embed type works fine.

**Pull request closed without merging**
