### PR TITLE
Chinese proofreading for 1-22

### PR DESCRIPTION
**Pull request by pigheadx**
Minor mistakes and typos fixed
Inconsistent across issues fixed
Unified space format

### CODE REVIEW

**Comment by Firerazer** [comment]
Huge work @pigheadx !!
@Conor12345 I let you simulate the website with this and see if pages are broken or not? from quick overview, seems fine for me

**Comment by DrMagPie** [comment]
@Firerazer https://deploy-preview-394--elegant-fermi-d94da2.netlify.app
P.S. Don't forget to change the language 😋

**Comment by Firerazer** [comment]
Issue21: code not formated

**Comment by Firerazer** [comment]
ok, code formating seems to be the preview only that do not support it.
Approved for me!!

**Review by Firerazer — APPROVED** [review]

**Pull request merged**
