### PR TITLE
remove modernizr-webp.js

### PR DESCRIPTION
**Pull request by justchen1369**

### CODE REVIEW

**Comment by justchen1369** [comment]
hmm, it appears that FA is used in the buttons on the bottom of the site.

**Comment by DrMagPie** [comment]
Language button 
arrows in page selector

**Comment by Conor12345** [comment]
Would this be a good time to switch to self hosting the primary fonts? I remember there was something about it being more beneficial since browser privacy rules have chanced. Also probably worth finally removing google analytics which I completely forgot to do.

**Comment by Conor12345** [comment]
I believe this is the font sled hosting thing I was thinking of: https://wpspeedmatters.com/self-host-google-fonts/

TLDR a primary advantage of Google Fonts was they were likely pre cached from other sites but this can't happen anymore cause cache segmenting. Google Fonts could be faster but it also adds more DNS checks and stuff so I suspect hosting the fonts ourselves would be faster

**Comment by justchen1369** [comment]
hmm, yeah. @YPetremann comments?

**Comment by YPetremann** [comment]
I don't see any good argument and counter-argument for the need to move to self host font-awesome.

**Comment by CanadaHonk** [comment]
Imo:
Self-hosting font awesome isn't strictly needed however self-hosting core fonts for the page is a good idea.

**Comment by Zr4g0n** [comment]
The icons that are used from FA are simple enough that they could be replaced by inline SVGs instead.

**Comment by justchen1369** [comment]
based on ctrl+f, there are 11 FA icons that are used, so I don't think we should remove it.

**Pull request merged**
