### PR TITLE
Enable PWA Functionality

### LINKED ISSUE #109: Make the site into a PWA

### PR DESCRIPTION
**Pull request by justchen1369**
I'd like to first get your inputs on things like caching strategies for various files, what files to cache, theme color, and background color.

### CODE REVIEW

**Comment by justchen1369** [comment]
live site: https://silly-noyce-84abf1.netlify.app/

**Comment by Conor12345** [comment]
Fixes #109

**Comment by justchen1369** [comment]
@Conor12345 any thoughts on the caching strategies specified in `service-worker.js`?

**Comment by Conor12345** [comment]
> 
> 
> @Conor12345 any thoughts on the caching strategies specified in `service-worker.js`?

Not particularly, mostly we want caching to allow us to work on slow internet well and have the option for nice high quality images. I'm not super experienced with PWA's so don't know the specific on the technical side. Happy to test and advise but @DrMagPie would be better to ask for technical questions.

**Comment by DrMagPie** [comment]
@justchen1369 Could you please give some details on differences in these strategies? Might be some references.

**Comment by justchen1369** [comment]
@DrMagPie https://developers.google.com/web/tools/workbox/modules/workbox-strategies lists all of the relevant strategies.

**Comment by DrMagPie** [comment]
okay so in the end we have:
`networkFirst` for `html` 
`staleWhileRevalidate` for `js`, `css` and `Imgur`
`cacheFirst` for images.

I think that a good choice of strategies. But might be worth moving Imgur to cash first? like other images.

**Comment by justchen1369** [comment]
One problem is that `start_url` in the manifest needs to be different for each of the localizations.

**Comment by DrMagPie** [comment]
this should do the trick `"start_url": "{% if site.active_lang == site.default_lang %}{{site.url}}{% else %}{{site.url}}/{{site.active_lang}}{% endif %}",`
and you need to add 
```
---
---
```
to the top of file so Jekyll will render it 

result should look like this 
```json
---
---
{
  "name": "Alternative Friday Factorio Facts",
  "short_name": "Alt-F4",
  "theme_color": "#414040",
  "background_color": "#414040",
  "display": "standalone",
  "scope": "/",
  "start_url": "{% if site.active_lang == site.default_lang %}{{site.url}}{% else %}{{site.url}}/{{site.active_lang}}{% endif %}",
  "icons": [
    {
      "src": "/assets/GLOBAL/img/Alt-F4-icon_512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "/assets/GLOBAL/img/Alt-F4-icon_256x256.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

**Comment by justchen1369** [comment]
Checklist:

- [ ] the correct files are cached at the right times
   - [ ] networkFirst for html
   - [ ] staleWhileRevalidate for js, css and Imgur
   - [ ] cacheFirst for images and fonts
- [ ] a smart precache strategy
   - [ ] ???
- [ ] start_url is changed for each locale

**Comment by justchen1369** [comment]
should be ready for testing 👍

**Comment by justchen1369** [comment]
testing url: https://silly-noyce-84abf1.netlify.app/

**Comment by Conor12345** [comment]
Just thought, this needs updating from master before we push it out, make sure we don't have conflicts and all new features still work.

**Comment by justchen1369** [comment]
I'm on it

**Comment by justchen1369** [comment]
Maybe someday, but not today. (also, it is now actually possible to have 0 open pull requests so yay)

**Pull request closed without merging**
