### PR TITLE
dynamic stuff

### PR DESCRIPTION
**Pull request by DrMagPie**

### CODE REVIEW

**Comment by Conor12345** [comment]
Translations:
- [ ] CS
- [x] DE
- [x] ES
- [x] FR
- [x] IT
- [ ] NL
- [ ] PL
- [x] RU
- [ ] UA
- [x] ZH

**Comment by LovelySanta** [comment]
I expect DU stands for Dutch? that should be NL

**Comment by Firerazer** [comment]
corrected - the NL will be subject of another PR (will link it when done)

**Review by Firerazer — APPROVED** [review]
CS/PL/UA will be done later, the files are way too much outdated

**Pull request merged**
